### ISSUE TITLE
CPE is not considered in the codec result

### ISSUE THREAD

**Issue by criestlav** [logstash-plugins/logstash-codec-nmap#7]
Hi, 
I am working with nmap. I am trying to send to elasticsearch the result of the analysis through logstash-codec-nmap but It does not consider the field that contains the CPE.
Is there any solution to keep in mind that field?

Thank you!

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
